import os
import sys
from pathlib import Path

def get_files(patterns, extensions):
    files = []
    for pattern in patterns:
        path = Path(pattern)
        if path.exists():
            for ext in extensions:
                for file in sorted(path.rglob(f"*{ext}")):
                    files.append(str(file))
    return sorted(set(files))

def format_cmake_list(name, files):
    if not files:
        return f"set({name})\n"

    lines = [f"set({name}"]
    for file in files:
        lines.append(f"    {file}")
    lines.append(")")
    return "\n".join(lines) + "\n"

def main():
    script_dir = Path(__file__).parent
    os.chdir(script_dir)

    groups = {
        "GAME_FILES": (
            ["src/c", "src/d", "src/f_ap", "src/f_op", "src/f_pc", "src/m_Do"],
            [".cpp"]
        ),
        "JSYS_FILES": (
            ["src/JSystem"],
            [".cpp"]
        ),
        "SSYS_FILES": (
            ["src/SSystem"],
            [".cpp"]
        ),
        "DOLPHIN_FILES": (
            ["src/dolphin"],
            [".c"]
        ),
    }

    output = []
    for name, (patterns, extensions) in groups.items():
        files = get_files(patterns, extensions)
        output.append(format_cmake_list(name, files))

    output_file = script_dir / "tp.cmake"
    with open(output_file, "w") as f:
        f.write("# Generated by generate_cmake.py\n")
        f.writelines(output)

    # Print summary
    for name, (patterns, extensions) in groups.items():
        files = get_files(patterns, extensions)

if __name__ == "__main__":
    main()
